vich_uploader:
    db_driver: orm

    mappings:
       pdf_wageSlip:
           uri_prefix: /pdf/wageslips
           upload_destination: '%kernel.project_dir%/public/pdf/wageslips'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
